### ISSUE TITLE
Blog Post of Density Data

### ISSUE THREAD

**Issue by jzf2101** [adicu/density#112]
Hey 

Attached is a link to the notebook with my plots I was gonna share at devfest.

Let me know what edits you think I should make before we put it up on the blog:

http://nbviewer.ipython.org/github/jzf2101/density/blob/master/datasci/density_demo.ipynb

**Comment by natebrennand** [comment]
on `In [24]`, is that the average count per location, not the average for the campus? Could we clarify that?

this looks really good

**Comment by jzf2101** [comment]
It's the average count per group_id for that time of day, yes.  I agree the language is a big vague.  Do you have suggestions to clarify?

**Comment by natebrennand** [comment]
I would just include the entire sum of the whole campus. I think that would make the numbers more meaningful

**Comment by jzf2101** [comment]
No problem. Check again, I redid the plot.

**Comment by natebrennand** [comment]
It's not rendering the last few images for me, idk if that's a problem.

[in] 6: I think this should be "What spaces do we have?"
[in] 9: I think we should point out that this is only study space & dining halls, not all of Columbia.

**Comment by jzf2101** [comment]
@natebrennand changed the language

**Comment by natebrennand** [comment]
[in]15 s/Comumbia/Columbia

I'm satisfied with this, can someone else take a glance though? @thebrianzeng

**Comment by thebrianzeng** [comment]
all the plots look great! before we publicize it, i think we should add some more detailed explanations for what's going on. also, do we want a version without all the code for the non-programming audience?

**Comment by thebrianzeng** [comment]
oh, is there anyway to remove the warning?

```WARNING: pylab import has clobbered these variables: ['plt']
`%matplotlib` prevents importing * from pylab and numpy```

**Comment by jzf2101** [comment]
@thebrianzeng

Agree with both your comments lets discuss in person Friday how to flesh
out the text?

On Feb 24, 2015, at 17:08, thebrianzeng <notifications@github.com> wrote:

oh, is there anyway to remove the warning?

WARNING: pylab import has clobbered these variables: ['plt']
`%matplotlib` prevents importing * from pylab and numpy

—
Reply to this email directly or view it on GitHub
<https://github.com/adicu/density/issues/112#issuecomment-75857339>.

**Comment by thebrianzeng** [comment]
sounds good - i'm super excited to get this out!

**Comment by natebrennand** [comment]
Let's make sure we get this posted.

@chmullig made these neat webapp (https://chmullig.shinyapps.io/relative_density/) that hooks into the API. If you want to link to it just let him know since he'd like to clean it up a bit.
@ Chris, see the iPython notebook link above if you're interested in checking it out.

**Comment by chmullig** [comment]
:notebook:  :+1:  :+1:

**Comment by jzf2101** [comment]
@chmullig Sure! Please make any adjustments and keep us posted so we can add the link. Do you have a repo I can reference if I have questions?

**Comment by chmullig** [comment]
Just pushed it up (had to make a new repo, since the old one had my API key in it...)

https://github.com/chmullig/relative_density

**Comment by jzf2101** [comment]
@chmullig Cool thanks! Are you planning to make any changes before I post?

**Comment by chmullig** [comment]
@jzf2101 I just added a couple links at the bottom. Didn't have time to change it to make it more friendly.

**Comment by jzf2101** [comment]
Hey again I made some changes to reference the tool @chmullig built.  I'm packaging it together in a pull request we can put up.  It has a blog post as a markdown and a notebook with the same content
