### ISSUE TITLE
links to density.adicu.com/auth in docs page need relative

### ISSUE THREAD

**Issue by danrschlosser** [adicu/density#119]
in the second paragraph under "Get an API Key"

**Comment by jzf2101** [comment]
Ok I can fix this :+1:

**Comment by jzf2101** [comment]
@danrschlosser 

Line 14 of density/density/templates/docs.html says 

```html
<p>To access this API, you'll need to <a href="http://density.adicu.com/auth">get an API key</a> by logging in with your Columbia-affiliated email.</p>
```

So I think that resolves that unless you're referrring to somewhere else?

**Comment by natebrennand** [comment]
That link should be a relative link (`/auth`) if possible, not a hard link.

**Comment by jzf2101** [comment]
I'll relabel the title to reflect that
