### ISSUE TITLE
Wrong Email error seems slightly aggressive

### ISSUE THREAD

**Issue by danrschlosser** [adicu/density#121]
![screen shot 2015-03-01 at 11 14 34 pm](https://cloud.githubusercontent.com/assets/2433509/6435303/1a722750-c069-11e4-9799-18ac4fcdede6.png)

**Comment by swbae31** [comment]
lol

**Comment by jzf2101** [comment]
I edited the language to be less harsh, but I can't figure out how to test becuase when I click on the get access page it automatically logs me in.  How do I test the error?

**Comment by natebrennand** [comment]
if you test this using an incognito browser it shouldn't login automatically.
Alternatively, you can alter the checking code and then take a screenshot of the new message.

**Comment by jzf2101** [comment]
Ahh ok cool

**Comment by jzf2101** [comment]
Tried testing it in incognito mode I get this error:

`File not found: "client_secrets.json"`

Am I supposed to have that json?

**Comment by thebrianzeng** [comment]
yeah, you should have it to do the authentication. it should be in the
slack channel somewhere i believe

**Comment by jzf2101** [comment]
![screen shot 2015-04-04 at 15 10 17](https://cloud.githubusercontent.com/assets/1373035/6994166/cab60b3a-dadc-11e4-8c9c-c126165b26d7.png)

Font remains the same.  Language softened.  Let me know what you think and I'll turn it into a pull request
