### ISSUE TITLE
Link to the API from the homepage

### ISSUE THREAD

**Issue by danrschlosser** [adicu/density#122]
Many people might go to density and never know that we have an API!

**Comment by chmullig** [comment]
...woah... I didn't even see this issue... Yet somehow GitHub thinks my likely broken patch closes it? Crazy.

**Comment by natebrennand** [comment]
i added the comment that generates a link. when/if you PR is merged it will close this issue automatically

**Comment by jzf2101** [comment]
See a6b465a
