### ISSUE TITLE
Can't Seem To Run Locally?

### ISSUE THREAD

**Issue by jzf2101** [adicu/density#133]
When I run density.py

![screen shot 2015-03-21 at 15 15 37](https://cloud.githubusercontent.com/assets/1373035/6766441/2bf66b66-cfdd-11e4-911a-2b4580da044f.png)

And I go to the socket, I get this error:

![screen shot 2015-03-21 at 15 14 37](https://cloud.githubusercontent.com/assets/1373035/6766440/162e94b6-cfdd-11e4-812d-429249415169.png)

**Comment by thebrianzeng** [comment]
hmm, can you try printing out the exception in the function that handles it?

**Comment by jzf2101** [comment]
How would I do that? The output from terminal is what I get when I go to `localhost:5000`

**Comment by thebrianzeng** [comment]
in density.py after line 95, add a `print e`

**Comment by jzf2101** [comment]
Ah! That solved it! I was able to fix it :smiley:
