### ISSUE TITLE
Map popup alignment

### ISSUE THREAD

**Issue by RaymondXu** [adicu/density#136]
On Safari 8.0.4, OS X 10.10.2, the map popups become misaligned after refreshing the page a few times. From testing, the popups also realign themselves after multiple refreshes.

Update: Issue also appears on Chrome.

Incorrect (Mouse is hovering over the upper right red rectangle):
![screen shot 2015-03-27 at 4 44 07 pm](https://cloud.githubusercontent.com/assets/7762515/6876699/8f63244c-d4a0-11e4-9867-b03ac6156b69.png)

Correct:
![screen shot 2015-03-27 at 4 45 30 pm](https://cloud.githubusercontent.com/assets/7762515/6876717/b7ccd554-d4a0-11e4-9afc-3753cd0f855d.png)

**Comment by natebrennand** [comment]
please include screenshots

**Comment by evantarrh** [comment]
lol @RaymondXu fixed this accidentally???????????? :+1: :+1: :100:

**Comment by RaymondXu** [comment]
Seems fixed by #161 for reference.
