### ISSUE TITLE
Put Blog Post on the ADI website

### ISSUE THREAD

**Issue by jzf2101** [adicu/density#137]
We now have the markdown for the blogpost - how do we put in on the website?

**Comment by natebrennand** [comment]
I made you an account: https://adicu.com/admin/
You should be able to create an account and login with your Columbia email.

If you have an questions about the UI you can ping me on slack.

**Comment by jzf2101** [comment]
Thanks!

**Comment by natebrennand** [comment]
?
I don't see it: https://adicu.com/blog

**Comment by evantarrh** [comment]
![screenshot 2015-05-01 16 00 02](https://cloud.githubusercontent.com/assets/5566223/7436390/4d2ea38a-f01b-11e4-92c1-c7efd6e8cd32.png)

Looks like the alt text is missing.

**Comment by evantarrh** [comment]
also I think the title should be the only h1

**Comment by natebrennand** [comment]
Oh, I don't get the alt text error on Chrome 42.0.2311.90 (64-bit) with Mavericks

**Comment by jzf2101** [comment]
@evantarrh I don't have publishing rights to fix that h1 formatting issue
