### ISSUE TITLE
Need to find a place for the information currently in the about boxes

### ISSUE THREAD

**Issue by RaymondXu** [adicu/density#150]
By design decision, the home page's blue box is being deleted and replaced by a slim nav bar of the same background color. We need to decide where to put the about statements. Also there are similar about statements on each page that need to be moved around.

-Maybe a separate ABOUT html page
-Maybe move map svg credits to bottom

Home page currently looks like:

![screen shot 2015-04-03 at 5 21 57 pm](https://cloud.githubusercontent.com/assets/7762515/6989117/fb87d142-da25-11e4-8c9e-b3eec77f8662.png)

We want it to look something like:

![screen shot 2015-04-03 at 5 21 46 pm](https://cloud.githubusercontent.com/assets/7762515/6989120/ff1f0c1c-da25-11e4-84be-dd9cc6ff11a9.png)

**Comment by evantarrh** [comment]
This would be a much-needed change. I like the idea of having a separate about page, and I agree that we should put the map credits on the bottom of the map page.

What's the status on the navbar? Should this be part of that branch?

**Comment by RaymondXu** [comment]
Basic navbar (as appears in the pic) is done. Works on mobile too--just that all the tabs don't fill the entire width. The information refactoring is the last thing to do before I submit a PR.

**Comment by evantarrh** [comment]
Okay cool! Yeah you should move forward with those changes, they all sound good :man:
