### ISSUE TITLE
Map javascript on Safari sometimes not loading fast enough-- results in static SVG map with no interactability.

### ISSUE THREAD

**Issue by RaymondXu** [adicu/density#160]
![screen shot 2015-04-17 at 3 54 03 pm](https://cloud.githubusercontent.com/assets/7762515/7209793/01975f90-e51a-11e4-8483-516551a6f822.png)

**Comment by RaymondXu** [comment]
Closed by #161.

**Comment by evantarrh** [comment]
When viewing in incognito mode, all buildings show up as red & it only works on reload. Investigating this issue now.
