### ISSUE TITLE
Button in navbar size needs to be aligned

### ISSUE THREAD

**Issue by jzf2101** [adicu/density#162]
![screen shot 2015-04-17 at 17 09 30](https://cloud.githubusercontent.com/assets/1373035/7210997/9823b51c-e524-11e4-9c67-27c0836ca837.png)

**Comment by evantarrh** [comment]
can you elaborate on this?

**Comment by RaymondXu** [comment]
I got this. The dark blue indicator that you are on a specific page is not filling the entire height of the navbar sometimes
