### ISSUE TITLE
Map banner won't go away!

### ISSUE THREAD

**Issue by blvns** [adicu/density#166]
@evantarrh, 
The map banner isn't removed from the homepage even when you click on the "x". I had this problem in Chrome, Firefox, and Safari. 
![screen shot 2015-04-24 at 3 15 12 pm](https://cloud.githubusercontent.com/assets/8763732/7326712/8765a2be-ea95-11e4-9c54-92917d87ce9c.png)
^^Still there after clicking on the x :(

**Comment by RaymondXu** [comment]
This bug happens on the live version. I think it might be fixed in the currect repo version.

**Comment by evantarrh** [comment]
Raymond's right––what's currently on master is fixed. I'll tell @thebrianzeng to deploy.
