### ISSUE TITLE
create window functionality

### ISSUE THREAD

**Issue by thebrianzeng** [adicu/density#29]

**Comment by jzf2101** [comment]
Hey you guys I think this is done right?

**Comment by maclyn** [comment]
If this refers to the /window endpoint, this is definitely done.

**Comment by jzf2101** [comment]
Yeah I'm wondering that. Could someone confirm?

On Feb 1, 2015, at 16:31, Maclyn B <notifications@github.com> wrote:

If this refers to the /window endpoint, this is definitely done.

—
Reply to this email directly or view it on GitHub
<https://github.com/adicu/density/issues/29#issuecomment-72385304>.

**Comment by natebrennand** [comment]
it'd be more "done" if there were tests written for it
