### ISSUE TITLE
Return datetimes should be in ISO 8601

### ISSUE THREAD

**Issue by natebrennand** [adicu/density#53]
This should be resolved by setting the database driver to do it for us if possible.

If that is not feasible, then we will need to call [`isoformat()`](https://docs.python.org/2/library/datetime.html#datetime.datetime.isoformat) or something similar on each record being returned.

**Comment by jzf2101** [comment]
@natebrennand What did we do to close this?

**Comment by natebrennand** [comment]
duplicate of #40 which is where all the discussion is
(sorry, meant to include this)
