### ISSUE TITLE
add a privacy notice to the home page

### ISSUE THREAD

**Issue by thebrianzeng** [adicu/density#62]

**Comment by natebrennand** [comment]
ping

**Comment by RaymondXu** [comment]
If this is necessary, we can add it to the new about page (which needs more content).

**Comment by jzf2101** [comment]
@thebrianzeng What kind of language would you want?

**Comment by thebrianzeng** [comment]
unsure, i forget what the context was for this issue. maybe @natebrennand
knows?

**Comment by natebrennand** [comment]
I don't remember at all.

I would guess that this was to have something detailing that the data we get from CUIT is anonymous?

**Comment by thebrianzeng** [comment]
sounds about right
