### ISSUE TITLE
/docs/building_info takes too long

### ISSUE THREAD

**Issue by thebrianzeng** [adicu/density#87]
it's going through everything in the database right now.

**Comment by natebrennand** [comment]
solution: create a materialized view?

**Comment by thebrianzeng** [comment]
oh that would be cool - but in the interest of time, temporary solution for
now: using the latest dump?

**Comment by natebrennand** [comment]
Ya, even just put in a static list for now lol

**Comment by jzf2101** [comment]
We fixed this for now in eaff4e4027c11bd0ae99ea6430f0af3a4615ceb8, but there's still #92
