### ISSUE TITLE
route to get latest capacities instead of device count

### ISSUE THREAD

**Issue by thebrianzeng** [adicu/density#88]
it would be nice to get the percentages, instead of just the device counts.

**Comment by swbae31** [comment]
/latest/capacity/
/latest/capacity/group/<group_id>
/latest/capacity/bulding/<parent_id>
..... and for all routes i guess?

I'll make a function like
calculate_group_capacity(group_names, full_cap_data)
to use it all the calculation part (calculation done in capacity()).

**Comment by swbae31** [comment]
Or lets not update the routes but rather add the percentage key to the response json.

So its 
   "client_count": 136, 
    "fullness" : 54,                                                              <-- in percentage
      "dump_time": "Sat, 01 Nov 2014 19:45:00 GMT", 
      "group_id": 23, 
      "group_name": "Uris/Watson Library", 
      "parent_id": 2, 
      "parent_name": "Uris"
    },

**Comment by swbae31** [comment]
Made the key "percent_full" type float

**Comment by swbae31** [comment]
#108
